# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-12-08 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20221208_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='texts',
        ),
        migrations.AddField(
            model_name='item',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
